### ISSUE TITLE
Menu don't work for small screen

### ISSUE THREAD

**Issue by Esquimor** [archethic-foundation/aeweb#24]
### Describe the problem you discovered

I have put the website for small screen (see screenshot)

![image](https://github.com/archethic-foundation/aeweb/assets/32507951/5a094ddf-7c67-4fe2-ac62-9ca0ccebedcc)

The menu icon don't work when I click on it.

Step to reproduce:

1. Open the website
2. Use a small screen
3. Click on the menu icon.
![image](https://github.com/archethic-foundation/aeweb/assets/32507951/e2c3cabf-0bc6-44de-854a-e084f7b87130)

Maybe link to: https://github.com/archethic-foundation/aeweb/issues/12

### Describe the solution you'd like

When i click on the button, I want to see a menu.

**Comment by redDwarf03** [comment]
see globally https://github.com/archethic-foundation/aeweb/issues/12
Some works should be finished to have a responsive app
